/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.carmanager.gui;

import cz.muni.fi.pv168.carmanager.backend.Brand;
import cz.muni.fi.pv168.carmanager.backend.Car;
import cz.muni.fi.pv168.carmanager.backend.CarManagerImpl;
import cz.muni.fi.pv168.carmanager.backend.LeaseManagerImpl;
import cz.muni.fi.pv168.carmanager.databasetools.IllegalEntityException;
import java.awt.Frame;
import java.util.ResourceBundle;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.DataSource;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.apache.commons.dbcp2.BasicDataSource;


public class CarManagerGUI extends javax.swing.JFrame {

    private final String[] brands = {"BMW", "MERCEDES_BENZ", "SKODA", "VOLGA", "MOSKVIC", "KIA", "VARBURG", "TATRA"};
    private DataSource dataSource;
    private CarManagerImpl carManager;
    private LeaseManagerImpl leaseManager;
    private CarSwingWorker carSwingWorker;
    //private LeaseSwingWorker leaseSwingWorker;

    private static final Logger logger = Logger.getLogger(
            LeaseManagerImpl.class.getName());

    /**
     * Creates new form CarManagerGUI
     */
    public CarManagerGUI() {

        dataSource = prepareDataSource();
        carManager = new CarManagerImpl(dataSource);
        leaseManager = new LeaseManagerImpl();
        leaseManager.setDataSource(dataSource);

        initComponents();

        this.jTabbedPane.setTitleAt(0, ResourceBundle.getBundle("strings").getString("carPanel"));
        this.jTabbedPane.setTitleAt(1, ResourceBundle.getBundle("strings").getString("leasePanel"));

        carSwingWorker = new CarSwingWorker(Operations.ADD_ALL, (Car) null);
        carSwingWorker.execute();

    }

    private DataSource prepareDataSource() {

        BasicDataSource ds = new BasicDataSource();
        ds.setDriverClassName("org.apache.derby.jdbc.ClientDriver");
        ds.setUrl("jdbc:derby://localhost:1527/Car");
        ds.setUsername("marek");
        ds.setPassword("marek");

        return ds;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCarDialog = new javax.swing.JDialog((Frame) null,true);
        jLabel3 = new javax.swing.JLabel();
        addCarDialogBrandsComboBox = new javax.swing.JComboBox<String>();
        jLabel4 = new javax.swing.JLabel();
        addCarDialogLicencePlateTextField = new javax.swing.JTextField();
        addCarDialogSubmitButton = new javax.swing.JButton();
        addCarConfirmationDialog = new javax.swing.JDialog((Frame)null,true);
        addCarConfirmationCancel = new javax.swing.JButton();
        addCarConfirmationYes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        editCarDialog = new javax.swing.JDialog((Frame) null,true);
        jLabel7 = new javax.swing.JLabel();
        editCarDialogBrandsComboBox = new javax.swing.JComboBox<String>();
        jLabel8 = new javax.swing.JLabel();
        editCarDialogLicencePlateTextField = new javax.swing.JTextField();
        editCarDialogSubmitButton = new javax.swing.JButton();
        editCarConfirmationDialog = new javax.swing.JDialog((Frame)null,true);
        editCarConfirmationCancel = new javax.swing.JButton();
        editCarConfirmationYes = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        deleteCarConfirmationDialog = new javax.swing.JDialog((Frame)null,true);
        deleteCarConfirmationCancel = new javax.swing.JButton();
        deleteCarConfirmationYes = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        showAllCarsByBrandDialog = new javax.swing.JDialog((Frame) null,true);
        jLabel11 = new javax.swing.JLabel();
        showCarsByBrandDialogBrandsComboBox = new javax.swing.JComboBox<String>();
        showAllCarsByBrandDialogSubmitButton = new javax.swing.JButton();
        showAllCarsBetweenDatesDialog = new javax.swing.JDialog((Frame) null,true);
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        showAllCarsBetweenDateSubmitButton = new javax.swing.JButton();
        showAllCarsBetweenDatesStartDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        showAllCarsBetweenDatesEndDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        showAllLeasesBetweenDatesDialog = new javax.swing.JDialog((Frame) null,true);
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        showAllLeasesBetweenDateSubmitButton = new javax.swing.JButton();
        showAllLeasesBetweenDatesStartDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        showAllLeaseBetweenDatesEndDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        addLeaseDialog = new javax.swing.JDialog((Frame) null,true);
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        addLeaseDialogSubmitButton = new javax.swing.JButton();
        addLeaseEnterCustomerFullNameTextField = new javax.swing.JTextField();
        addLeaseDialogStartDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        addLeaseDialogEndDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel20 = new javax.swing.JLabel();
        addLeaseDialogCarsComboBox = new javax.swing.JComboBox<String>();
        addLeaseConfirmationDialog = new javax.swing.JDialog((Frame)null,true);
        addLeaseConfirmationCancel = new javax.swing.JButton();
        addLeaseConfirmationYes = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        editLeaseDialog = new javax.swing.JDialog((Frame) null,true);
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        editLeaseDialogSubmitButton = new javax.swing.JButton();
        editLeaseEnterCustomerFullNameTextField = new javax.swing.JTextField();
        editLeaseDialogStartDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel24 = new javax.swing.JLabel();
        editLeaseDialogEndDateDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel25 = new javax.swing.JLabel();
        editLeaseDialogCarsComboBox = new javax.swing.JComboBox<String>();
        editLeaseConfirmationDialog = new javax.swing.JDialog((Frame)null,true);
        editLeaseConfirmationCancel = new javax.swing.JButton();
        editLeaseConfirmationYes = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        deleteLeaseConfirmationDialog = new javax.swing.JDialog((Frame)null,true);
        deleteLeaseConfirmationCancel = new javax.swing.JButton();
        deleteLeaseConfirmationYes = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        carPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carsTable = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        carPanelShowAllCarsByBrandButton = new javax.swing.JButton();
        carPanelShowAllCarsButton = new javax.swing.JButton();
        carPaneShowAllFreeCarsBetweenDates = new javax.swing.JButton();
        carPanelAddCarButton = new javax.swing.JButton();
        carPanelEditCarButton = new javax.swing.JButton();
        carPanelDeleteCarButton = new javax.swing.JButton();
        leasePanel = new javax.swing.JPanel();
        leaseTable = new javax.swing.JScrollPane();
        leasesTable = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        leasePanelShowAllLeasesButton = new javax.swing.JButton();
        leasePanelShowAllLeasesBetweenDatesButton = new javax.swing.JButton();
        leasePanelAddLeaseButton = new javax.swing.JButton();
        leasePanelEditLeaseButton = new javax.swing.JButton();
        leasePanelDeleteLeaseButton = new javax.swing.JButton();

        addCarDialog.setTitle("Add car");
        addCarDialog.setResizable(false);
        addCarDialog.setSize(new java.awt.Dimension(400, 250));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("Enter brand:");

        addCarDialogBrandsComboBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addCarDialogBrandsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(brands));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Enter licence plate:");

        addCarDialogLicencePlateTextField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addCarDialogSubmitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addCarDialogSubmitButton.setText("Submit");
        addCarDialogSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCarDialogSubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addCarDialogLayout = new javax.swing.GroupLayout(addCarDialog.getContentPane());
        addCarDialog.getContentPane().setLayout(addCarDialogLayout);
        addCarDialogLayout.setHorizontalGroup(
            addCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(addCarDialogBrandsComboBox, 0, 294, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCarDialogLicencePlateTextField))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCarDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCarDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        addCarDialogLayout.setVerticalGroup(
            addCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCarDialogBrandsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCarDialogLicencePlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addCarDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addCarConfirmationDialog.setTitle("Confirmation");
        addCarConfirmationDialog.setResizable(false);
        addCarConfirmationDialog.setSize(new java.awt.Dimension(365, 110));

        addCarConfirmationCancel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addCarConfirmationCancel.setText("Cancel");
        addCarConfirmationCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCarConfirmationCancelMouseClicked(evt);
            }
        });

        addCarConfirmationYes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addCarConfirmationYes.setText("Yes");
        addCarConfirmationYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCarConfirmationYesMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel6.setText("Do you really want to add car ?");

        javax.swing.GroupLayout addCarConfirmationDialogLayout = new javax.swing.GroupLayout(addCarConfirmationDialog.getContentPane());
        addCarConfirmationDialog.getContentPane().setLayout(addCarConfirmationDialogLayout);
        addCarConfirmationDialogLayout.setHorizontalGroup(
            addCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCarConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCarConfirmationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCarConfirmationYes)
                .addGap(118, 118, 118))
            .addGroup(addCarConfirmationDialogLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        addCarConfirmationDialogLayout.setVerticalGroup(
            addCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCarConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(addCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCarConfirmationCancel)
                    .addComponent(addCarConfirmationYes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editCarDialog.setTitle("Edit car");
        editCarDialog.setResizable(false);
        editCarDialog.setSize(new java.awt.Dimension(400, 250));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel7.setText("Enter brand:");

        editCarDialogBrandsComboBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editCarDialogBrandsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(brands));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel8.setText("Enter licence plate:");

        editCarDialogLicencePlateTextField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        editCarDialogSubmitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editCarDialogSubmitButton.setText("Submit");
        editCarDialogSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCarDialogSubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editCarDialogLayout = new javax.swing.GroupLayout(editCarDialog.getContentPane());
        editCarDialog.getContentPane().setLayout(editCarDialogLayout);
        editCarDialogLayout.setHorizontalGroup(
            editCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(editCarDialogBrandsComboBox, 0, 294, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCarDialogLicencePlateTextField))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCarDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editCarDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        editCarDialogLayout.setVerticalGroup(
            editCarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editCarDialogBrandsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editCarDialogLicencePlateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editCarDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editCarConfirmationDialog.setTitle("Confirmation");
        editCarConfirmationDialog.setResizable(false);
        editCarConfirmationDialog.setSize(new java.awt.Dimension(365, 110));

        editCarConfirmationCancel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editCarConfirmationCancel.setText("Cancel");
        editCarConfirmationCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCarConfirmationCancelMouseClicked(evt);
            }
        });

        editCarConfirmationYes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editCarConfirmationYes.setText("Yes");
        editCarConfirmationYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCarConfirmationYesMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("Do you really want to update car ?");

        javax.swing.GroupLayout editCarConfirmationDialogLayout = new javax.swing.GroupLayout(editCarConfirmationDialog.getContentPane());
        editCarConfirmationDialog.getContentPane().setLayout(editCarConfirmationDialogLayout);
        editCarConfirmationDialogLayout.setHorizontalGroup(
            editCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCarConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editCarConfirmationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCarConfirmationYes)
                .addGap(118, 118, 118))
            .addGroup(editCarConfirmationDialogLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel9)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        editCarConfirmationDialogLayout.setVerticalGroup(
            editCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCarConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(editCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCarConfirmationCancel)
                    .addComponent(editCarConfirmationYes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteCarConfirmationDialog.setTitle("Confirmation");
        deleteCarConfirmationDialog.setResizable(false);
        deleteCarConfirmationDialog.setSize(new java.awt.Dimension(365, 110));

        deleteCarConfirmationCancel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        deleteCarConfirmationCancel.setText("Cancel");
        deleteCarConfirmationCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCarConfirmationCancelMouseClicked(evt);
            }
        });

        deleteCarConfirmationYes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        deleteCarConfirmationYes.setText("Yes");
        deleteCarConfirmationYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteCarConfirmationYesMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel10.setText("Do you really want to delete car ?");

        javax.swing.GroupLayout deleteCarConfirmationDialogLayout = new javax.swing.GroupLayout(deleteCarConfirmationDialog.getContentPane());
        deleteCarConfirmationDialog.getContentPane().setLayout(deleteCarConfirmationDialogLayout);
        deleteCarConfirmationDialogLayout.setHorizontalGroup(
            deleteCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCarConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(deleteCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteCarConfirmationDialogLayout.createSequentialGroup()
                        .addComponent(deleteCarConfirmationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCarConfirmationYes)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteCarConfirmationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(51, 51, 51))))
        );
        deleteCarConfirmationDialogLayout.setVerticalGroup(
            deleteCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCarConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(deleteCarConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCarConfirmationCancel)
                    .addComponent(deleteCarConfirmationYes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        showAllCarsByBrandDialog.setTitle("Show all cars by brands");
        showAllCarsByBrandDialog.setResizable(false);
        showAllCarsByBrandDialog.setSize(new java.awt.Dimension(400, 170));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel11.setText("Enter brand:");

        showCarsByBrandDialogBrandsComboBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        showCarsByBrandDialogBrandsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(brands));

        showAllCarsByBrandDialogSubmitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        showAllCarsByBrandDialogSubmitButton.setText("Submit");
        showAllCarsByBrandDialogSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllCarsByBrandDialogSubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout showAllCarsByBrandDialogLayout = new javax.swing.GroupLayout(showAllCarsByBrandDialog.getContentPane());
        showAllCarsByBrandDialog.getContentPane().setLayout(showAllCarsByBrandDialogLayout);
        showAllCarsByBrandDialogLayout.setHorizontalGroup(
            showAllCarsByBrandDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showAllCarsByBrandDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showAllCarsByBrandDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(showCarsByBrandDialogBrandsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showAllCarsByBrandDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showAllCarsByBrandDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        showAllCarsByBrandDialogLayout.setVerticalGroup(
            showAllCarsByBrandDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showAllCarsByBrandDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showCarsByBrandDialogBrandsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(showAllCarsByBrandDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        showAllCarsBetweenDatesDialog.setTitle("Show all cars between dates");
        showAllCarsBetweenDatesDialog.setResizable(false);
        showAllCarsBetweenDatesDialog.setSize(new java.awt.Dimension(400, 250));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel12.setText("Choose start date:");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel13.setText("Choose end date:");

        showAllCarsBetweenDateSubmitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        showAllCarsBetweenDateSubmitButton.setText("Submit");
        showAllCarsBetweenDateSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllCarsBetweenDateSubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout showAllCarsBetweenDatesDialogLayout = new javax.swing.GroupLayout(showAllCarsBetweenDatesDialog.getContentPane());
        showAllCarsBetweenDatesDialog.getContentPane().setLayout(showAllCarsBetweenDatesDialogLayout);
        showAllCarsBetweenDatesDialogLayout.setHorizontalGroup(
            showAllCarsBetweenDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showAllCarsBetweenDatesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showAllCarsBetweenDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllCarsBetweenDatesStartDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllCarsBetweenDatesEndDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showAllCarsBetweenDatesDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showAllCarsBetweenDateSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        showAllCarsBetweenDatesDialogLayout.setVerticalGroup(
            showAllCarsBetweenDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showAllCarsBetweenDatesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showAllCarsBetweenDatesStartDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showAllCarsBetweenDatesEndDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(showAllCarsBetweenDateSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        showAllLeasesBetweenDatesDialog.setTitle("Show all cars between dates");
        showAllLeasesBetweenDatesDialog.setResizable(false);
        showAllLeasesBetweenDatesDialog.setSize(new java.awt.Dimension(400, 250));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel16.setText("Choose start date:");

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel17.setText("Choose end date:");

        showAllLeasesBetweenDateSubmitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        showAllLeasesBetweenDateSubmitButton.setText("Submit");
        showAllLeasesBetweenDateSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showAllLeasesBetweenDateSubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout showAllLeasesBetweenDatesDialogLayout = new javax.swing.GroupLayout(showAllLeasesBetweenDatesDialog.getContentPane());
        showAllLeasesBetweenDatesDialog.getContentPane().setLayout(showAllLeasesBetweenDatesDialogLayout);
        showAllLeasesBetweenDatesDialogLayout.setHorizontalGroup(
            showAllLeasesBetweenDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showAllLeasesBetweenDatesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(showAllLeasesBetweenDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllLeasesBetweenDatesStartDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllLeaseBetweenDatesEndDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showAllLeasesBetweenDatesDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showAllLeasesBetweenDateSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        showAllLeasesBetweenDatesDialogLayout.setVerticalGroup(
            showAllLeasesBetweenDatesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showAllLeasesBetweenDatesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showAllLeasesBetweenDatesStartDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showAllLeaseBetweenDatesEndDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(showAllLeasesBetweenDateSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addLeaseDialog.setTitle("Add lease");
        addLeaseDialog.setResizable(false);
        addLeaseDialog.setSize(new java.awt.Dimension(400, 395));

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel18.setText("Enter customer full name:");

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel19.setText("Choose start date:");

        addLeaseDialogSubmitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addLeaseDialogSubmitButton.setText("Submit");
        addLeaseDialogSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLeaseDialogSubmitButtonMouseClicked(evt);
            }
        });

        addLeaseEnterCustomerFullNameTextField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel5.setText("Choose end date:");

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel20.setText("Choose car:");

        addLeaseDialogCarsComboBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addLeaseDialogCarsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout addLeaseDialogLayout = new javax.swing.GroupLayout(addLeaseDialog.getContentPane());
        addLeaseDialog.getContentPane().setLayout(addLeaseDialogLayout);
        addLeaseDialogLayout.setHorizontalGroup(
            addLeaseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLeaseDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addLeaseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLeaseDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addLeaseDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addLeaseDialogLayout.createSequentialGroup()
                        .addGroup(addLeaseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLeaseEnterCustomerFullNameTextField)
                            .addComponent(addLeaseDialogStartDateDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(addLeaseDialogEndDateDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLeaseDialogCarsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addLeaseDialogLayout.setVerticalGroup(
            addLeaseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLeaseDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addLeaseEnterCustomerFullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addLeaseDialogStartDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addLeaseDialogEndDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addLeaseDialogCarsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addLeaseDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addLeaseConfirmationDialog.setTitle("Confirmation");
        addLeaseConfirmationDialog.setResizable(false);
        addLeaseConfirmationDialog.setSize(new java.awt.Dimension(365, 110));

        addLeaseConfirmationCancel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addLeaseConfirmationCancel.setText("Cancel");
        addLeaseConfirmationCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLeaseConfirmationCancelMouseClicked(evt);
            }
        });

        addLeaseConfirmationYes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addLeaseConfirmationYes.setText("Yes");
        addLeaseConfirmationYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLeaseConfirmationYesMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel21.setText("Do you really want to add lease ?");

        javax.swing.GroupLayout addLeaseConfirmationDialogLayout = new javax.swing.GroupLayout(addLeaseConfirmationDialog.getContentPane());
        addLeaseConfirmationDialog.getContentPane().setLayout(addLeaseConfirmationDialogLayout);
        addLeaseConfirmationDialogLayout.setHorizontalGroup(
            addLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLeaseConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(addLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLeaseConfirmationDialogLayout.createSequentialGroup()
                        .addComponent(addLeaseConfirmationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLeaseConfirmationYes)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLeaseConfirmationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(54, 54, 54))))
        );
        addLeaseConfirmationDialogLayout.setVerticalGroup(
            addLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLeaseConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(addLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addLeaseConfirmationCancel)
                    .addComponent(addLeaseConfirmationYes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editLeaseDialog.setTitle("Edit lease");
        editLeaseDialog.setResizable(false);
        editLeaseDialog.setSize(new java.awt.Dimension(400, 400));

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel22.setText("Enter customer full name:");

        jLabel23.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel23.setText("Choose start date:");

        editLeaseDialogSubmitButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editLeaseDialogSubmitButton.setText("Submit");
        editLeaseDialogSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editLeaseDialogSubmitButtonMouseClicked(evt);
            }
        });

        editLeaseEnterCustomerFullNameTextField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel24.setText("Choose end date:");

        jLabel25.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel25.setText("Choose car:");

        editLeaseDialogCarsComboBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editLeaseDialogCarsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout editLeaseDialogLayout = new javax.swing.GroupLayout(editLeaseDialog.getContentPane());
        editLeaseDialog.getContentPane().setLayout(editLeaseDialogLayout);
        editLeaseDialogLayout.setHorizontalGroup(
            editLeaseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLeaseDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editLeaseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editLeaseDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editLeaseDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editLeaseDialogLayout.createSequentialGroup()
                        .addGroup(editLeaseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editLeaseEnterCustomerFullNameTextField)
                            .addComponent(editLeaseDialogStartDateDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addComponent(editLeaseDialogEndDateDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editLeaseDialogCarsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        editLeaseDialogLayout.setVerticalGroup(
            editLeaseDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLeaseDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editLeaseEnterCustomerFullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editLeaseDialogStartDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editLeaseDialogEndDateDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editLeaseDialogCarsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editLeaseDialogSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editLeaseConfirmationDialog.setTitle("Confirmation");
        editLeaseConfirmationDialog.setResizable(false);
        editLeaseConfirmationDialog.setSize(new java.awt.Dimension(365, 110));

        editLeaseConfirmationCancel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editLeaseConfirmationCancel.setText("Cancel");
        editLeaseConfirmationCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editLeaseConfirmationCancelMouseClicked(evt);
            }
        });

        editLeaseConfirmationYes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        editLeaseConfirmationYes.setText("Yes");
        editLeaseConfirmationYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editLeaseConfirmationYesMouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel26.setText("Do you really want to edit lease ?");

        javax.swing.GroupLayout editLeaseConfirmationDialogLayout = new javax.swing.GroupLayout(editLeaseConfirmationDialog.getContentPane());
        editLeaseConfirmationDialog.getContentPane().setLayout(editLeaseConfirmationDialogLayout);
        editLeaseConfirmationDialogLayout.setHorizontalGroup(
            editLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLeaseConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(editLeaseConfirmationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editLeaseConfirmationYes)
                .addGap(118, 118, 118))
            .addGroup(editLeaseConfirmationDialogLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editLeaseConfirmationDialogLayout.setVerticalGroup(
            editLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLeaseConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(editLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLeaseConfirmationCancel)
                    .addComponent(editLeaseConfirmationYes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deleteLeaseConfirmationDialog.setTitle("Confirmation");
        deleteLeaseConfirmationDialog.setResizable(false);
        deleteLeaseConfirmationDialog.setSize(new java.awt.Dimension(365, 110));

        deleteLeaseConfirmationCancel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        deleteLeaseConfirmationCancel.setText("Cancel");
        deleteLeaseConfirmationCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLeaseConfirmationCancelMouseClicked(evt);
            }
        });

        deleteLeaseConfirmationYes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        deleteLeaseConfirmationYes.setText("Yes");
        deleteLeaseConfirmationYes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLeaseConfirmationYesMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel27.setText("Do you really want to delete lease ?");

        javax.swing.GroupLayout deleteLeaseConfirmationDialogLayout = new javax.swing.GroupLayout(deleteLeaseConfirmationDialog.getContentPane());
        deleteLeaseConfirmationDialog.getContentPane().setLayout(deleteLeaseConfirmationDialogLayout);
        deleteLeaseConfirmationDialogLayout.setHorizontalGroup(
            deleteLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLeaseConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(deleteLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteLeaseConfirmationDialogLayout.createSequentialGroup()
                        .addComponent(deleteLeaseConfirmationCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteLeaseConfirmationYes)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteLeaseConfirmationDialogLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(54, 54, 54))))
        );
        deleteLeaseConfirmationDialogLayout.setVerticalGroup(
            deleteLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLeaseConfirmationDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(deleteLeaseConfirmationDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteLeaseConfirmationCancel)
                    .addComponent(deleteLeaseConfirmationYes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car manager app");
        setResizable(false);
        setSize(new java.awt.Dimension(961, 600));

        jTabbedPane.setBackground(new java.awt.Color(215, 52, 52));
        jTabbedPane.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        carPanel.setLayout(new java.awt.BorderLayout());

        carsTable.setModel(new CarTableModel());
        jScrollPane1.setViewportView(carsTable);

        carPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        carPanelShowAllCarsByBrandButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        carPanelShowAllCarsByBrandButton.setText("Show all cars by brand");
        carPanelShowAllCarsByBrandButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carPanelShowAllCarsByBrandButtonMouseClicked(evt);
            }
        });
        jToolBar1.add(carPanelShowAllCarsByBrandButton);

        carPanelShowAllCarsButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        carPanelShowAllCarsButton.setText("Show all cars");
        carPanelShowAllCarsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carPanelShowAllCarsButtonMouseClicked(evt);
            }
        });
        jToolBar1.add(carPanelShowAllCarsButton);

        carPaneShowAllFreeCarsBetweenDates.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        carPaneShowAllFreeCarsBetweenDates.setText("Show all free cars between dates");
        carPaneShowAllFreeCarsBetweenDates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carPaneShowAllFreeCarsBetweenDatesMouseClicked(evt);
            }
        });
        jToolBar1.add(carPaneShowAllFreeCarsBetweenDates);

        carPanelAddCarButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        carPanelAddCarButton.setText("Add car");
        carPanelAddCarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carPanelAddCarButtonMouseClicked(evt);
            }
        });
        carPanelAddCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carPanelAddCarButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(carPanelAddCarButton);

        carPanelEditCarButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        carPanelEditCarButton.setText("Edit car");
        carPanelEditCarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carPanelEditCarButtonMouseClicked(evt);
            }
        });
        jToolBar1.add(carPanelEditCarButton);

        carPanelDeleteCarButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        carPanelDeleteCarButton.setText("Delete car");
        carPanelDeleteCarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carPanelDeleteCarButtonMouseClicked(evt);
            }
        });
        jToolBar1.add(carPanelDeleteCarButton);

        carPanel.add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane.addTab("Car", carPanel);

        leasePanel.setLayout(new java.awt.BorderLayout());

        leasesTable.setModel(new LeaseTableModel(carManager));
        leaseTable.setViewportView(leasesTable);

        leasePanel.add(leaseTable, java.awt.BorderLayout.CENTER);

        jToolBar2.setRollover(true);

        leasePanelShowAllLeasesButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        leasePanelShowAllLeasesButton.setText("Show all leases");
        jToolBar2.add(leasePanelShowAllLeasesButton);

        leasePanelShowAllLeasesBetweenDatesButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        leasePanelShowAllLeasesBetweenDatesButton.setText("Show all leases between dates");
        leasePanelShowAllLeasesBetweenDatesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leasePanelShowAllLeasesBetweenDatesButtonMouseClicked(evt);
            }
        });
        jToolBar2.add(leasePanelShowAllLeasesBetweenDatesButton);

        leasePanelAddLeaseButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        leasePanelAddLeaseButton.setText("Add lease");
        leasePanelAddLeaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leasePanelAddLeaseButtonMouseClicked(evt);
            }
        });
        jToolBar2.add(leasePanelAddLeaseButton);

        leasePanelEditLeaseButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        leasePanelEditLeaseButton.setText("Edit lease");
        leasePanelEditLeaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leasePanelEditLeaseButtonMouseClicked(evt);
            }
        });
        jToolBar2.add(leasePanelEditLeaseButton);

        leasePanelDeleteLeaseButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        leasePanelDeleteLeaseButton.setText("Delete lease");
        leasePanelDeleteLeaseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leasePanelDeleteLeaseButtonMouseClicked(evt);
            }
        });
        jToolBar2.add(leasePanelDeleteLeaseButton);

        leasePanel.add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jTabbedPane.addTab("Lease", leasePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCarDialogSubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCarDialogSubmitButtonMouseClicked
        this.addCarConfirmationDialog.setVisible(true);
    }//GEN-LAST:event_addCarDialogSubmitButtonMouseClicked

    private void addCarConfirmationCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCarConfirmationCancelMouseClicked
        this.addCarConfirmationDialog.setVisible(false);
    }//GEN-LAST:event_addCarConfirmationCancelMouseClicked

    private void addCarConfirmationYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCarConfirmationYesMouseClicked
        this.addCarConfirmationDialog.setVisible(false);
        this.addCarDialog.setVisible(false);

        Car car = new Car();
        car.setBrand(Brand.valueOf((String) addCarDialogBrandsComboBox.getSelectedItem()));
        car.setLicencePlate(addCarDialogLicencePlateTextField.getText());

        try {
            carSwingWorker = new CarSwingWorker(Operations.ADD, car);
            carSwingWorker.execute();
        } catch (IllegalArgumentException | IllegalEntityException ex) {
            String msg = "Add car exception";
            logger.log(Level.SEVERE, msg, ex);
            showErrorDialog(ex.getMessage());
        }
    }//GEN-LAST:event_addCarConfirmationYesMouseClicked

    private void editCarConfirmationYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCarConfirmationYesMouseClicked
        this.editCarConfirmationDialog.setVisible(false);
        this.editCarDialog.setVisible(false);

        CarTableModel model = (CarTableModel) carsTable.getModel();

        Car car = model.getSelectetdCar(carsTable.getSelectedRow());
        car.setBrand(Brand.valueOf((String) editCarDialogBrandsComboBox.getSelectedItem()));
        car.setLicencePlate(editCarDialogLicencePlateTextField.getText());

        try {
            carSwingWorker = new CarSwingWorker(Operations.EDIT, car);
            carSwingWorker.execute();
        } catch (IllegalArgumentException | IllegalEntityException ex) {
            String msg = "Add car exception";
            logger.log(Level.SEVERE, msg, ex);
            showErrorDialog(ex.getMessage());
        }
    }//GEN-LAST:event_editCarConfirmationYesMouseClicked

    private void editCarDialogSubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCarDialogSubmitButtonMouseClicked
        this.editCarConfirmationDialog.setVisible(true);
    }//GEN-LAST:event_editCarDialogSubmitButtonMouseClicked

    private void editCarConfirmationCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCarConfirmationCancelMouseClicked
        this.editCarConfirmationDialog.setVisible(false);
    }//GEN-LAST:event_editCarConfirmationCancelMouseClicked

    private void deleteCarConfirmationCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCarConfirmationCancelMouseClicked
        this.deleteCarConfirmationDialog.setVisible(false);
    }//GEN-LAST:event_deleteCarConfirmationCancelMouseClicked

    private void deleteCarConfirmationYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCarConfirmationYesMouseClicked
        this.deleteCarConfirmationDialog.setVisible(false);

        CarTableModel model = (CarTableModel) carsTable.getModel();

        Car car = model.getSelectetdCar(carsTable.getSelectedRow());

        try {
            carSwingWorker = new CarSwingWorker(Operations.DELETE, car);
            carSwingWorker.execute();
        } catch (IllegalArgumentException ex) {
            String msg = "Delete car exception";
            logger.log(Level.SEVERE, msg, ex);
            showErrorDialog(ex.getMessage());
        }
    }//GEN-LAST:event_deleteCarConfirmationYesMouseClicked

    private void showAllCarsByBrandDialogSubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllCarsByBrandDialogSubmitButtonMouseClicked
        this.showAllCarsByBrandDialog.setVisible(false);
        Brand brand = Brand.valueOf((String) showCarsByBrandDialogBrandsComboBox.getSelectedItem());
        try {
            carSwingWorker = new CarSwingWorker(Operations.ADD_BY_BRAND, brand);
            carSwingWorker.execute();
        } catch (IllegalArgumentException ex) {
            String msg = "Show cars by brnad exception";
            logger.log(Level.SEVERE, msg, ex);
            showErrorDialog(ex.getMessage());
        }
    }//GEN-LAST:event_showAllCarsByBrandDialogSubmitButtonMouseClicked

    private void showAllCarsBetweenDateSubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllCarsBetweenDateSubmitButtonMouseClicked
        this.showAllCarsBetweenDatesDialog.setVisible(false);      
    }//GEN-LAST:event_showAllCarsBetweenDateSubmitButtonMouseClicked

    private void carPaneShowAllFreeCarsBetweenDatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carPaneShowAllFreeCarsBetweenDatesMouseClicked
        this.showAllCarsBetweenDatesDialog.setVisible(true);
    }//GEN-LAST:event_carPaneShowAllFreeCarsBetweenDatesMouseClicked

    private void carPanelShowAllCarsByBrandButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carPanelShowAllCarsByBrandButtonMouseClicked
        this.showAllCarsByBrandDialog.setVisible(true);
    }//GEN-LAST:event_carPanelShowAllCarsByBrandButtonMouseClicked

    private void carPanelDeleteCarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carPanelDeleteCarButtonMouseClicked
        int carRow = carsTable.getSelectedRow();
        if (carRow == -1) {
            // TO DO showErrorDialog(ResourceBundle.getBundle("strings").getString("carNotSelectedDelete"));
            return;
        }
        this.deleteCarConfirmationDialog.setVisible(true);
    }//GEN-LAST:event_carPanelDeleteCarButtonMouseClicked

    private void carPanelEditCarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carPanelEditCarButtonMouseClicked
        int carRow = carsTable.getSelectedRow();
        if (carRow == -1) {
            // TO DO showErrorDialog(ResourceBundle.getBundle("strings").getString("carNotSelectedDelete"));
            return;
        }
        this.editCarDialog.setVisible(true);
    }//GEN-LAST:event_carPanelEditCarButtonMouseClicked

    private void carPanelAddCarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carPanelAddCarButtonMouseClicked
        addCarDialog.setVisible(true);

    }//GEN-LAST:event_carPanelAddCarButtonMouseClicked

    private void showAllLeasesBetweenDateSubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showAllLeasesBetweenDateSubmitButtonMouseClicked
        this.showAllLeasesBetweenDatesDialog.setVisible(false);
    }//GEN-LAST:event_showAllLeasesBetweenDateSubmitButtonMouseClicked

    private void addLeaseConfirmationYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLeaseConfirmationYesMouseClicked
        this.addLeaseConfirmationDialog.setVisible(false);
        this.addLeaseDialog.setVisible(false);
    }//GEN-LAST:event_addLeaseConfirmationYesMouseClicked

    private void addLeaseConfirmationCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLeaseConfirmationCancelMouseClicked
        this.addLeaseConfirmationDialog.setVisible(false);
    }//GEN-LAST:event_addLeaseConfirmationCancelMouseClicked

    private void addLeaseDialogSubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLeaseDialogSubmitButtonMouseClicked
        this.addLeaseConfirmationDialog.setVisible(true);
    }//GEN-LAST:event_addLeaseDialogSubmitButtonMouseClicked

    private void leasePanelAddLeaseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leasePanelAddLeaseButtonMouseClicked
        this.addLeaseDialog.setVisible(true);
    }//GEN-LAST:event_leasePanelAddLeaseButtonMouseClicked

    private void editLeaseConfirmationYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editLeaseConfirmationYesMouseClicked
        this.editLeaseConfirmationDialog.setVisible(false);
        this.editLeaseDialog.setVisible(false);
    }//GEN-LAST:event_editLeaseConfirmationYesMouseClicked

    private void editLeaseConfirmationCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editLeaseConfirmationCancelMouseClicked
        this.editLeaseConfirmationDialog.setVisible(false);
    }//GEN-LAST:event_editLeaseConfirmationCancelMouseClicked

    private void editLeaseDialogSubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editLeaseDialogSubmitButtonMouseClicked
        this.editLeaseConfirmationDialog.setVisible(true);
    }//GEN-LAST:event_editLeaseDialogSubmitButtonMouseClicked

    private void leasePanelEditLeaseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leasePanelEditLeaseButtonMouseClicked
        this.editLeaseDialog.setVisible(true);
    }//GEN-LAST:event_leasePanelEditLeaseButtonMouseClicked

    private void deleteLeaseConfirmationYesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLeaseConfirmationYesMouseClicked
        this.deleteLeaseConfirmationDialog.setVisible(false);
    }//GEN-LAST:event_deleteLeaseConfirmationYesMouseClicked

    private void deleteLeaseConfirmationCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLeaseConfirmationCancelMouseClicked
        this.deleteLeaseConfirmationDialog.setVisible(false);
    }//GEN-LAST:event_deleteLeaseConfirmationCancelMouseClicked

    private void leasePanelDeleteLeaseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leasePanelDeleteLeaseButtonMouseClicked
        this.deleteLeaseConfirmationDialog.setVisible(true);
    }//GEN-LAST:event_leasePanelDeleteLeaseButtonMouseClicked

    private void leasePanelShowAllLeasesBetweenDatesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leasePanelShowAllLeasesBetweenDatesButtonMouseClicked
        this.showAllLeasesBetweenDatesDialog.setVisible(true);
    }//GEN-LAST:event_leasePanelShowAllLeasesBetweenDatesButtonMouseClicked

    private void carPanelAddCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carPanelAddCarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carPanelAddCarButtonActionPerformed

    private void carPanelShowAllCarsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carPanelShowAllCarsButtonMouseClicked
        try {
            carSwingWorker = new CarSwingWorker(Operations.ADD_ALL, (Car) null);
            carSwingWorker.execute();
        } catch (IllegalArgumentException ex) {
            String msg = "Show all cars exception";
            logger.log(Level.SEVERE, msg, ex);
            showErrorDialog(ex.getMessage());
        }
     }//GEN-LAST:event_carPanelShowAllCarsButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarConfirmationCancel;
    private javax.swing.JDialog addCarConfirmationDialog;
    private javax.swing.JButton addCarConfirmationYes;
    private javax.swing.JDialog addCarDialog;
    private javax.swing.JComboBox<String> addCarDialogBrandsComboBox;
    private javax.swing.JTextField addCarDialogLicencePlateTextField;
    private javax.swing.JButton addCarDialogSubmitButton;
    private javax.swing.JButton addLeaseConfirmationCancel;
    private javax.swing.JDialog addLeaseConfirmationDialog;
    private javax.swing.JButton addLeaseConfirmationYes;
    private javax.swing.JDialog addLeaseDialog;
    private javax.swing.JComboBox<String> addLeaseDialogCarsComboBox;
    private org.jdesktop.swingx.JXDatePicker addLeaseDialogEndDateDatePicker;
    private org.jdesktop.swingx.JXDatePicker addLeaseDialogStartDateDatePicker;
    private javax.swing.JButton addLeaseDialogSubmitButton;
    private javax.swing.JTextField addLeaseEnterCustomerFullNameTextField;
    private javax.swing.JButton carPaneShowAllFreeCarsBetweenDates;
    private javax.swing.JPanel carPanel;
    private javax.swing.JButton carPanelAddCarButton;
    private javax.swing.JButton carPanelDeleteCarButton;
    private javax.swing.JButton carPanelEditCarButton;
    private javax.swing.JButton carPanelShowAllCarsButton;
    private javax.swing.JButton carPanelShowAllCarsByBrandButton;
    private javax.swing.JTable carsTable;
    private javax.swing.JButton deleteCarConfirmationCancel;
    private javax.swing.JDialog deleteCarConfirmationDialog;
    private javax.swing.JButton deleteCarConfirmationYes;
    private javax.swing.JButton deleteLeaseConfirmationCancel;
    private javax.swing.JDialog deleteLeaseConfirmationDialog;
    private javax.swing.JButton deleteLeaseConfirmationYes;
    private javax.swing.JButton editCarConfirmationCancel;
    private javax.swing.JDialog editCarConfirmationDialog;
    private javax.swing.JButton editCarConfirmationYes;
    private javax.swing.JDialog editCarDialog;
    private javax.swing.JComboBox<String> editCarDialogBrandsComboBox;
    private javax.swing.JTextField editCarDialogLicencePlateTextField;
    private javax.swing.JButton editCarDialogSubmitButton;
    private javax.swing.JButton editLeaseConfirmationCancel;
    private javax.swing.JDialog editLeaseConfirmationDialog;
    private javax.swing.JButton editLeaseConfirmationYes;
    private javax.swing.JDialog editLeaseDialog;
    private javax.swing.JComboBox<String> editLeaseDialogCarsComboBox;
    private org.jdesktop.swingx.JXDatePicker editLeaseDialogEndDateDatePicker;
    private org.jdesktop.swingx.JXDatePicker editLeaseDialogStartDateDatePicker;
    private javax.swing.JButton editLeaseDialogSubmitButton;
    private javax.swing.JTextField editLeaseEnterCustomerFullNameTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JPanel leasePanel;
    private javax.swing.JButton leasePanelAddLeaseButton;
    private javax.swing.JButton leasePanelDeleteLeaseButton;
    private javax.swing.JButton leasePanelEditLeaseButton;
    private javax.swing.JButton leasePanelShowAllLeasesBetweenDatesButton;
    private javax.swing.JButton leasePanelShowAllLeasesButton;
    private javax.swing.JScrollPane leaseTable;
    private javax.swing.JTable leasesTable;
    private javax.swing.JButton showAllCarsBetweenDateSubmitButton;
    private javax.swing.JDialog showAllCarsBetweenDatesDialog;
    private org.jdesktop.swingx.JXDatePicker showAllCarsBetweenDatesEndDateDatePicker;
    private org.jdesktop.swingx.JXDatePicker showAllCarsBetweenDatesStartDateDatePicker;
    private javax.swing.JDialog showAllCarsByBrandDialog;
    private javax.swing.JButton showAllCarsByBrandDialogSubmitButton;
    private org.jdesktop.swingx.JXDatePicker showAllLeaseBetweenDatesEndDateDatePicker;
    private javax.swing.JButton showAllLeasesBetweenDateSubmitButton;
    private javax.swing.JDialog showAllLeasesBetweenDatesDialog;
    private org.jdesktop.swingx.JXDatePicker showAllLeasesBetweenDatesStartDateDatePicker;
    private javax.swing.JComboBox<String> showCarsByBrandDialogBrandsComboBox;
    // End of variables declaration//GEN-END:variables

    private void showErrorDialog(String errorMessage) {

        String[] choices = {"OK"};
        int response = JOptionPane.showOptionDialog(this, errorMessage, ResourceBundle.getBundle("strings").getString("error"),
                JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null, choices, choices[0]);
    }

    private enum Operations {

        ADD_ALL, ADD, EDIT, DELETE, ADD_BY_BRAND;

    }

    private class CarSwingWorker extends SwingWorker<Void, Void> {

        private Operations operation;
        private Car car;
        private Brand brand;

        public CarSwingWorker(Operations operation, Car car) {
            this.operation = operation;
            this.car = car;
        }

        //novy konstruktor pre vypisovanie podla znaciek (neviem ci najlepsie riesenie)
        public CarSwingWorker(Operations operation, Brand brand) {
            this.operation = operation;
            this.brand = brand;
        }
        CarTableModel carsModel = (CarTableModel) carsTable.getModel();

        @Override
        protected Void doInBackground() throws Exception {
            switch (operation) {
                case ADD:
                    carManager.createCar(car);
                    break;
                case EDIT:
                    carManager.updateCar(car);
                    break;
                case DELETE:
                    carManager.deleteCar(car);
                    break;
                case ADD_ALL:
                    //zatial deletujem a nanovo nahazujem aby mi ich nevypisovalo viac krat (neefektivne mozes prepisat)
                    carsModel.deleteAllCars();
                    for (Car car : carManager.listAllCars()) {
                        carsModel.addCar(car);
                    }
                    break;
                case ADD_BY_BRAND:
                    //deletuejm a pridavam len tie ktore maju byt (neefektivne mozes prepisat)
                    carsModel.deleteAllCars();
                    for (Car car : carManager.listAllCarsByBrand(brand)) {
                        carsModel.addCar(car);

                    }
                    break;
            }
            return null;
        }

        @Override
        protected void done() {

            CarTableModel carsModel = (CarTableModel) carsTable.getModel();

            try {
                get();
                switch (operation) {
                    case ADD:
                        carsModel.addCar(car);
                        break;
                    case EDIT:
                        carsModel.fireTableDataChanged();
                        break;
                    case DELETE:
                        carsModel.deleteCar(car);
                        break;
                    case ADD_BY_BRAND:
                        carsModel.fireTableDataChanged();
                        break;
                }
            } catch (ExecutionException | InterruptedException ex) {
                showErrorDialog(ex.getMessage());
            }

        }

    }

}
